"""Write Spectre system environment metadata.

Purpose:
    Capture exact system metadata for reproducible M0 infrastructure and future
    experiments.

Design:
    The tool writes `environment/system_info.json` using Spectre's deterministic
    JSON writer. Conda environment exports and pip freeze files are generated by
    explicit documented commands, not by this Python tool.

Input:
    No command-line arguments are required in M0.

Output:
    `environment/system_info.json`.

Failure modes:
    Filesystem write failures raise project-specific manifest exceptions.

Complexity:
    O(1), excluding Git metadata lookup.

Examples:
    ```bash
    conda activate spectre
    python tools/write_environment_metadata.py
    ```

"""

from __future__ import annotations

from pathlib import Path

from spectre.constants import ENVIRONMENT_DIR_NAME, SYSTEM_INFO_NAME
from spectre.io.json import write_json
from spectre.utils.reproducibility import collect_environment_info


def main() -> int:
    """Write system metadata and return a process exit code."""
    output_path = Path(ENVIRONMENT_DIR_NAME) / SYSTEM_INFO_NAME
    write_json(collect_environment_info(Path.cwd()), output_path)
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
